### ISSUE TITLE
v0.4 To-do List

### ISSUE THREAD

**Issue by sxyazi** [sxyazi/yazi#1644]
- [x] Support auto-switching between dark/light flavors - https://github.com/sxyazi/yazi/issues/988.

- [x] Add support for named arguments (with `--`) in `--args` of the `plugin` command.

- [ ] Redesign `[filetype]` to improve performance and enhance functionality - https://github.com/sxyazi/yazi/issues/1518#issuecomment-2295521693.

- [x] Remove `x-` prefixes from mime-types as it's discouraged as per [rfc6838#section-3.4](https://datatracker.ietf.org/doc/html/rfc6838#section-3.4) - https://github.com/sxyazi/yazi/discussions/1663#discussioncomment-10705174.

- [x] Move `mode_normal`, `mode_select`, and `mode_unset` in `theme.toml` to a separate `[mode]` block with names like `normal_open`, `normal_close`, `select_open`, etc. (better names needed), https://github.com/sxyazi/yazi/issues/1228.

**Comment by spenserblack** [comment]
> Support auto-switching between dark/light flavors

Does this include shipping a preset light flavor to compliment the preset (dark) theme?

**Comment by sxyazi** [comment]
@spenserblack Done in https://github.com/sxyazi/yazi/pull/1946 🎉
